version: "3.9"
services:
  www:
    image: llm-challenge-ec2:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
