AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a DynamoDB table for challenges_prompts

Resources:
  ChallengesPromptsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: challenge_prompts
      BillingMode: PAY_PER_REQUEST # Consider using PAY_PER_REQUEST for more flexibility
      AttributeDefinitions:
        - AttributeName: prompt_id
          AttributeType: S
      KeySchema:
        - AttributeName: prompt_id
          KeyType: HASH
  ChallengesPromptsTableTest:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: challenge_prompts_test
      BillingMode: PAY_PER_REQUEST # Consider using PAY_PER_REQUEST for more flexibility
      AttributeDefinitions:
        - AttributeName: prompt_id
          AttributeType: S
      KeySchema:
        - AttributeName: prompt_id
          KeyType: HASH
  ChallengeResponsesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: challenge_responses
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: prompt_id
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
        - AttributeName: prompt_id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 50
  ChallengeResponsesTableTest:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: challenge_responses_test
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: prompt_id
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
        - AttributeName: prompt_id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  ProdLogGroup:
      Type: "AWS::Logs::LogGroup"
      Properties:
        LogGroupName: "challenge_prompts_log_group"
        RetentionInDays: 14
  ProdLogStream:
      Type: "AWS::Logs::LogStream"
      Properties:
        LogGroupName: "challenge_prompts_log_group"
        LogStreamName: "challenge_log_stream"
      DependsOn: ProdLogGroup
  TestLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "challenge_prompts_log_group_test"
      RetentionInDays: 14
  TestLogStream:
    Type: "AWS::Logs::LogStream"
    Properties:
      LogGroupName: "challenge_prompts_log_group_test"
      LogStreamName: "challenge_log_stream_test"
    DependsOn: TestLogGroup

